// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')

const { MAFWhen, performJSONObjectTransform } = require('@ln-maf/core')
const {setDefaultTimeout, When, BeforeAll, AfterAll } = require('@cucumber/cucumber')
setDefaultTimeout(60 * 1000);

let driver
BeforeAll( async function() {
  driver = await new Builder().forBrowser('firefox').build()
})
When('switch tab {int}', async function(tab) {
  let handles = await driver.getAllWindowHandles();
  var item=driver.switchTo()
  await item.window(handles[tab])
  await takeScreenshot.call(this)
})
When('open', async function() {
  const {url} = this.results
  await driver.get(url)
  await takeScreenshot.call(this)
})
AfterAll( async function() {
  await driver.quit()
})

async function takeScreenshot() {
  var screen=await driver.takeScreenshot()
  this.attach(screen, 'image/png' )

}
MAFWhen('get text from {jsonObject}', async function(obj) {
  obj=performJSONObjectTransform.call(this, obj)
  return await obj.getText()
})
MAFWhen('get active tab', async function() {
   return await driver.findElement(By.css(`a.active`))
})
MAFWhen('get element from text {string}', async function(text) {
  return await driver.findElement(By.xpath(`//*[text()='${text}']`))
})
MAFWhen('get source {string}', async function(str) {
  return await driver.findElement(By.xpath(`//*[@class='MuiIconButton-label']/*[@value='${str}']`))
})
MAFWhen('get clipboard content', async function() {
  const clipboardy = require('clipboardy');
  return clipboardy.readSync()
})
When('click {jsonObject}', async function(obj) {
  obj=performJSONObjectTransform.call(this, obj)
  var res= await obj.click()
  await takeScreenshot.call(this)
  return res
})
//Note index starts at one for xpath
MAFWhen('get multi tab {int}', async function(index) {
  return await driver.findElement(By.xpath(`(//*[@id='panel1c-header'])[${index}]`))
})
MAFWhen('get id {string}', async function(id) {
  return await driver.findElement(By.xpath(`(//*[@id='${id}'])`))
})
When('click tab {int}', async function(index) {
  // await driver.findElement(By.css(".fa-list")).click()
    await driver.findElement(By.xpath(`(//*[@class='nav nav-tabs']/*)[${index}]`)).click()  
    await takeScreenshot.call(this)
  })

